### ISSUE TITLE
BTH-1000 is not able to integrate with HA

### ISSUE THREAD

**Issue by Krzysztonek** [laszlojakab/homeassistant-bht1000#1]
Hi, @laszlojakab
I have exactly the same thermostat BHT-1000 from BECA as you mentioned in your HA Integration project.
Seems this integration is no longer working...
1. I'm not able to register this device in BECA Energy App: after loading the app settings page I need to press SEARCH NETWORK to go further (no possibility to insert SSID name manually). I checked the default server; _bestbeca.cn_ But no network is reachable for the application, regardless of choosing neither my home WiFi network nor the AP mode from the device. However, I'm able to connect the thermostat to my local network with [My Smart Thermostat](https://play.google.com/store/apps/details?id=com.thermostat.smart) app, installed from Google Play.
2. BHT-1000 integration has been correctly installed using HACS Home Assistant UI. But I don't see any [CONFIGURATION] button, where to point the right port: 8899. Moreover, I don't see any device entities on the Home Assistant Entities Global List. But il looks like I'm able to call bht1000.sync_time service to sync the clock (I checked this option with Node-RED only).

Now I'm stuck. What am I doing wrong? Would you please help me with resolving this critical issue? Otherwise, my thermostat will remain totally useless since I'm not going to control it via such a poor and stupid smartphone application. 

If you need any additional info, please feel free to ask, so I could provide whatever you may need to help me.

**Comment by laszlojakab** [comment]
Hi there,

> Seems this integration is no longer working...

Is this worked for you previously?

The integration is still working for me. I use HA core-2021.8.7

If the integration successfully installed, then you should click on add integration and search for BHT-1000 Wifi thermostat:

![image](https://user-images.githubusercontent.com/6196882/131879634-2bc07ec4-b86c-428c-996a-4bfbfadf90d9.png)

Next you should set IP address of the thermostat and give a name to it:

![image](https://user-images.githubusercontent.com/6196882/131879295-38ab68f6-d402-4b1d-b89b-be7bc7718b1f.png)

That's all the things you should do if your thermostat is compatible with the integration.
Do you have any error in logs related to the integration?

**Comment by Krzysztonek** [comment]
**Hi again @laszlojakab ** :)

It's awfully kind of you that you don't leave me alone and you are willing to help me. Really appreciate!

No, I have never tried to integrate this device with HA before. This is my first attempt.
HA supervisor: version 2021.08.1, HA core: version 2021.9.1, no SSL (instance accessible only from local host: http:/192.168.1.20:8123)

Yes, I'm able to reach the screen, where both host and device name are prompted:
![obraz](https://user-images.githubusercontent.com/87784133/131910353-44fef8dd-2335-4ac5-a54b-50d419cb9d45.png)
This means, that the integration has been successfully installed.

As I previously mentioned: I'm not able to register this device in BECA Energy app. Instead, I successfully registered it in [**My Smart Thermostat**](https://play.google.com/store/apps/details?id=com.thermostat.smart) app, downloaded from Google Play. This app is dedicated for BHT-1000 thermostat as per the user's manual attached to the device.
![obraz](https://user-images.githubusercontent.com/87784133/131918217-113f5fa9-45ca-453b-9a47-751341ccb569.png)

1.  I'm not sure if this is a difference for the device which application is being used for the device registration. Please clarify if it matters or not.
2.  As you can see, I'm reaching the screen with the BHT-1000 configuration settings. After registering the device using **My Smart Thermostat** app I checked with the network scanner, that the thermostat has IP 192.168.1.11 assigned. But whenever I'm trying to insert this IP to the BHT Configuration window, an _**invalid host**_ message is being displayed (see the screen). The same error occurs when I'm trying to set any other free IP from my local network.

Please, let me know what am I doing wrong? How to check where the root cause is, and where the truth lays if there are yet no BHT entries in the log file (this is obvious, because from HA perspective the device doesn't exist until it's correctly configured to be recognizable). 
And what mode to set on the device while trying to connect it to HA (WiFi mode? AP mode?)

Looking for your further support ;)

**Comment by laszlojakab** [comment]
I don't have My Smart Thermostat app installed. Could you check if you can register the thermostat in Tuya app? I have two versions of the thermostat and newer is not working with this integration, it works with Tuya integration.

**Comment by Krzysztonek** [comment]
**Hi @laszlojakab** 

Yes, I've successfully registered BHT-1000 in Tuya Smart Life App. To integrate this thermostat with HA, I installed [Tuya-v2 integration](https://github.com/tuya/tuya-home-assistant) passing successfully all required steps and finally getting this:
![image](https://user-images.githubusercontent.com/87784133/132497501-cc39660a-b7d0-4f91-ba4a-e95337e9866c.png)
I can see only one device (which is true. No other Tuya devices have been installed in my network):
![image](https://user-images.githubusercontent.com/87784133/132498001-5e9a630e-057d-4766-936c-d51abca77bec.png)
with one entity:
![image](https://user-images.githubusercontent.com/87784133/132498180-9584be8d-031c-431f-a233-84307d9fe2cc.png)
The status indicator: UNAVAILABLE (red dot with the exclamation sign on the right)

When trying to add a thermostat card to my dashboard, the following configuration card appears:
![image](https://user-images.githubusercontent.com/87784133/132498810-5796bf1a-26d7-4534-9da7-595bdfd87cda.png)

As you can see, there is no possibility to control this thermostat from the dashboard. It remains '_niedostepny_'=unavailable. Nothing to click, nothing to adjust, nothing to do with this card.

I believe there is nothing to do until BHT-1000 becomes available. But how to make it alive? This is the fundamental question..

**Comment by laszlojakab** [comment]
Hi, If you can register the thermostat in tuya app (and it is working from app) then it is a newer version of the thermostat (it won't work with this integration). If it is not working in HA then you should ask for help from Tuya V2 integration developers.

**Comment by Krzysztonek** [comment]
Ok, I will try to go this path.
Thank you!
